/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/locales/en`; params?: Router.UnknownInputParams; } | { pathname: `/locales`; params?: Router.UnknownInputParams; } | { pathname: `/locales/pt-BR`; params?: Router.UnknownInputParams; } | { pathname: `/_contexts/LocalizationContext`; params?: Router.UnknownInputParams; } | { pathname: `/_services/api`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/config`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/locales/en`; params?: Router.UnknownOutputParams; } | { pathname: `/locales`; params?: Router.UnknownOutputParams; } | { pathname: `/locales/pt-BR`; params?: Router.UnknownOutputParams; } | { pathname: `/_contexts/LocalizationContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_services/api`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/config${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/locales/en${`?${string}` | `#${string}` | ''}` | `/locales${`?${string}` | `#${string}` | ''}` | `/locales/pt-BR${`?${string}` | `#${string}` | ''}` | `/_contexts/LocalizationContext${`?${string}` | `#${string}` | ''}` | `/_services/api${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/locales/en`; params?: Router.UnknownInputParams; } | { pathname: `/locales`; params?: Router.UnknownInputParams; } | { pathname: `/locales/pt-BR`; params?: Router.UnknownInputParams; } | { pathname: `/_contexts/LocalizationContext`; params?: Router.UnknownInputParams; } | { pathname: `/_services/api`; params?: Router.UnknownInputParams; };
    }
  }
}
